//! Utilities for dealing with Lean FFI.

use std::{
    ffi::{c_char, CStr},
    sync::OnceLock,
};

use lean_sys::{
    lean_array_push, lean_box, lean_ctor_get, lean_dec, lean_dec_ref, lean_inc,
    lean_initialize_runtime_module_locked, lean_io_result_is_ok, lean_io_result_show_error,
    lean_is_ctor, lean_is_string, lean_mk_empty_array_with_capacity, lean_mk_string_from_bytes,
    lean_obj_res, lean_object, lean_ptr_tag, lean_string_cstr,
};
use thiserror::Error;

unsafe extern "C" {
    /// Auto-generated by Lean to initialize the Wavelet module.
    fn initialize_Wavelet(builtin: u8) -> lean_obj_res;
}

#[derive(Debug, Error)]
pub enum LeanObjectError {
    #[error("expected string")]
    ExpectedString,
    #[error("expected constructor")]
    ExpectedConstructor,
    #[error("expected Except value")]
    ExpectedExcept,
    #[error("UTF-8 error: {0}")]
    Utf8Error(#[from] std::str::Utf8Error),
}

/// A safe wrapper around owned `lean_object`,
/// adapted from [Cedar](https://github.com/cedar-policy/cedar-spec/blob/3eceb3c38836ffa13cef2e480af3bd092cc79e11/cedar-lean-ffi/src/lean_object.rs)
pub struct LeanObject {
    raw: *mut lean_object,
}

impl Drop for LeanObject {
    fn drop(&mut self) {
        unsafe {
            lean_dec(self.raw);
        }
    }
}

impl Clone for LeanObject {
    fn clone(&self) -> Self {
        unsafe {
            lean_inc(self.raw);
        }
        LeanObject { raw: self.raw }
    }
}

impl LeanObject {
    /// Returns the tag of the constructor
    /// (e.g., 0 for the first constructor in an inductive type).
    pub fn tag(&self) -> u8 {
        unsafe { lean_ptr_tag(self.raw) }
    }

    /// Creates an owned Lean `String` object.
    pub fn from_str(s: &str) -> Self {
        unsafe {
            // TODO: Check if `lean_mk_string_from_bytes` copies the string.
            LeanObject {
                raw: lean_mk_string_from_bytes(s.as_ptr(), s.len()),
            }
        }
    }

    /// Checks if the lean object is a Lean `String`,
    /// and if so, returns it as a Rust `&str`.
    pub fn as_str<'a>(&'a self) -> Result<&'a str, LeanObjectError> {
        if !unsafe { lean_is_string(self.raw) } {
            return Err(LeanObjectError::ExpectedString);
        }
        let cstr = unsafe { CStr::from_ptr(lean_string_cstr(self.raw) as *const c_char) };
        Ok(cstr.to_str()?)
    }

    /// Checks if the given lean object is a constructor.
    pub fn is_ctor<'a>(&'a self) -> bool {
        unsafe { lean_is_ctor(self.raw) }
    }

    /// Checks if the lean object is an Lean `Except` value,
    /// and if so, returns it as a Rust `Result`.
    ///
    /// TODO: This assumes that the fields are all lean objects (e.g., not `USize`, `Bool`, etc.).
    pub fn as_except<'a>(&'a self) -> Result<Result<LeanObject, LeanObject>, LeanObjectError> {
        if !self.is_ctor() {
            return Err(LeanObjectError::ExpectedConstructor);
        }
        match self.tag() {
            0 => {
                let raw = unsafe { lean_ctor_get(self.raw, 0) };
                let field = LeanObject { raw };
                unsafe { lean_inc(raw) };
                Ok(Err(field))
            }
            1 => {
                let raw = unsafe { lean_ctor_get(self.raw, 0) };
                let field = LeanObject { raw };
                unsafe { lean_inc(raw) };
                Ok(Ok(field))
            }
            _ => Err(LeanObjectError::ExpectedExcept),
        }
    }

    /// `lean_obj_arg` requires an owned `*mut lean_object`.
    pub fn to_lean_obj_arg(self) -> lean_sys::lean_obj_arg {
        let raw = self.raw;
        // Do not decrement the reference counter
        // since we are transferring ownership.
        std::mem::forget(self);
        raw
    }

    /// `lean_obj_res` contains an owned `*mut lean_object`.
    pub fn from_lean_obj_res(raw: lean_sys::lean_obj_res) -> Self {
        LeanObject { raw }
    }
}

/// A wrapper around Lean arrays (`Array`).
pub struct LeanArray {
    obj: LeanObject,
}

impl LeanArray {
    /// Creates an (owned) Lean array from a vector of Lean objects.
    pub fn from_vec(objs: Vec<LeanObject>) -> Self {
        let arr = unsafe {
            let capacity = lean_box(objs.len());
            let mut arr = lean_mk_empty_array_with_capacity(capacity);
            lean_dec(capacity);
            for obj in objs.into_iter() {
                arr = lean_array_push(arr, obj.to_lean_obj_arg());
            }
            arr
        };
        LeanArray {
            obj: LeanObject::from_lean_obj_res(arr),
        }
    }

    /// Returns the underlying Lean object.
    pub fn to_obj(self) -> LeanObject {
        self.obj
    }
}

/// Ensures that the Lean FFI is initialized.
/// See: https://lean-lang.org/doc/reference/latest/Run-Time-Code/Foreign-Function-Interface/#ffi
pub fn ensure_init_lean() {
    static INIT: OnceLock<()> = OnceLock::new();
    INIT.get_or_init(|| unsafe {
        lean_initialize_runtime_module_locked();
        let res = initialize_Wavelet(1);
        if lean_io_result_is_ok(res) {
            lean_dec_ref(res);
        } else {
            lean_io_result_show_error(res);
            lean_dec(res);
        }
    });
}
