"""
Abstractions for simulating designs compiled through the Polygeist + CIRCT
(dynamic HLS) pipeline.
"""

from __future__ import annotations
from typing import Any
from dataclasses import dataclass, field

import re
import cocotb
from cocotb.triggers import RisingEdge, ReadOnly

from .common import *

@dataclass
class CirctMemoryLoadPort:
    """A memory load port: addr (output from DUT), data (input to DUT). No done signal."""
    addr: HandshakeOutputPort
    data: HandshakeInputPort

    def init(self):
        self.addr.init()
        self.data.init()

    async def simulate(self, memory: CirctMemory):
        while True:
            addr = await self.addr.read()
            data = memory.load(addr.to_unsigned())
            assert data is not None, f"loading uninitialized memory at {addr}"
            await self.data.send(data)

@dataclass
class CirctMemoryStorePort:
    """
    A memory store port using a packed struct.
    The struct combines {address, data} into a single handshake channel.
    In the packed struct layout, address occupies the MSBs and data the LSBs.
    """
    port: HandshakeOutputPort # packed addr + data output
    done: HandshakeInputPort
    data_width: int

    def init(self):
        self.port.init()
        self.done.init()

    async def simulate(self, memory: CirctMemory):
        data_mask = (1 << self.data_width) - 1
        while True:
            val = await self.port.read()
            raw = val.to_unsigned()
            addr = raw >> self.data_width
            data = raw & data_mask
            # Sign-extend the data field
            if data >= (1 << (self.data_width - 1)):
                data -= (1 << self.data_width)
            memory.store(addr, data)
            await self.done.send()

@dataclass
class CirctMemory:
    """Simulated memory with load and store ports for a CIRCT design."""
    loads: list[CirctMemoryLoadPort]
    stores: list[CirctMemoryStorePort]
    state: MemoryState = field(default_factory=MemoryState)

    def init(self):
        for load in self.loads:
            load.init()
        for store in self.stores:
            store.init()

    def simulate(self):
        for load in self.loads:
            cocotb.start_soon(load.simulate(self))
        for store in self.stores:
            cocotb.start_soon(store.simulate(self))

    def store(self, addr: int, value: int):
        self.state.state[addr] = value

    def load(self, addr: int) -> Optional[int]:
        return self.state.state.get(addr)

class CirctDut:
    """
    Wrapper around a DUT instance compiled from a Polygeist + CIRCT design.

    Unlike WaveletDut which uses named memories, CIRCT designs generated by
    `hlstool` use numbered input ports (in0, in1, ...) that map positionally
    to function parameters, including array inputs that get compiled to memory
    interfaces.
    """

    # Patterns to identify port types from signal names
    INPUT_VALID_PATTERN = r"^in(\d+)_valid$"
    OUTPUT_VALID_PATTERN = r"^out(\d+)_valid$"
    LOAD_DATA_VALID_PATTERN = r"^in(\d+)_ld(\d+)_data_valid$"
    STORE_DONE_VALID_PATTERN = r"^in(\d+)_st(\d+)_done_valid$"

    STORE_DATA_WIDTH_PATTERN = (r"struct\s+packed\s*\{"
        r"\s*logic\s*\[\s*\d+\s*:\s*0\s*\]\s*address\s*;"
        r"\s*logic\s*\[\s*(\d+)\s*:\s*0\s*\]\s*data\s*;\s*"
        r"\}\s*")

    def __init__(self, dut, design_path: str):
        self.dut = dut
        # Ordered by input number; each entry is either a HandshakeInputPort
        # (scalar or zero-width control) or a CirctMemory.
        self.inputs: list[HandshakeInputPort | CirctMemory] = []
        self.outputs: list[HandshakeOutputPort] = []
        self.design_path = design_path
        with open(design_path) as f:
            self.design_source = f.read()

        self.find_all_ports()

    def parse_store_data_width(self, st_name: str) -> int:
        """
        Parse the data field width of a store port's packed struct from the SV source.
        TODO: This is a bit hacky.
        """
        pattern = CirctDut.STORE_DATA_WIDTH_PATTERN + re.escape(st_name)
        match = re.search(pattern, self.design_source)
        assert match is not None, \
            f"could not find struct declaration for store port {st_name} in {self.design_path}"
        return int(match.group(1)) + 1

    async def init(self):
        for inp in self.inputs:
            inp.init()
        for out in self.outputs:
            out.init()

        # Start memory simulations
        for inp in self.inputs:
            if isinstance(inp, CirctMemory):
                inp.simulate()

        # Reset
        self.dut.reset.value = 1
        await ReadOnly()
        await RisingEdge(self.dut.clock)
        self.dut.reset.value = 0
        await RisingEdge(self.dut.clock)

    def get_input_port(self, name: str) -> HandshakeInputPort:
        return HandshakeInputPort(
            data=getattr(self.dut, name, None),
            valid=getattr(self.dut, f"{name}_valid"),
            ready=getattr(self.dut, f"{name}_ready"),
            clock=self.dut.clock,
        )

    def get_output_port(self, name: str) -> HandshakeOutputPort:
        return HandshakeOutputPort(
            data=getattr(self.dut, name, None),
            valid=getattr(self.dut, f"{name}_valid"),
            ready=getattr(self.dut, f"{name}_ready"),
            clock=self.dut.clock,
        )

    def find_all_ports(self):
        """
        Build abstract wrappers around various DUT ports.
        """

        outputs: dict[int, HandshakeOutputPort] = {}
        mem_loads: dict[int, dict[int, CirctMemoryLoadPort]] = {}
        mem_stores: dict[int, dict[int, CirctMemoryStorePort]] = {}
        mem_input_numbers: set[int] = set()
        input_numbers: set[int] = set()

        for name in dir(self.dut):
            if match := re.match(CirctDut.LOAD_DATA_VALID_PATTERN, name):
                input_num = int(match.group(1))
                ld_idx = int(match.group(2))
                mem_input_numbers.add(input_num)
                loads = mem_loads.setdefault(input_num, {})
                assert ld_idx not in loads
                loads[ld_idx] = CirctMemoryLoadPort(
                    addr=self.get_output_port(f"in{input_num}_ld{ld_idx}_addr"),
                    data=self.get_input_port(f"in{input_num}_ld{ld_idx}_data"),
                )
            elif match := re.match(CirctDut.STORE_DONE_VALID_PATTERN, name):
                input_num = int(match.group(1))
                st_idx = int(match.group(2))
                mem_input_numbers.add(input_num)
                stores = mem_stores.setdefault(input_num, {})
                st_name = f"in{input_num}_st{st_idx}"
                assert st_idx not in stores
                stores[st_idx] = CirctMemoryStorePort(
                    port=self.get_output_port(st_name),
                    done=self.get_input_port(f"{st_name}_done"),
                    data_width=self.parse_store_data_width(st_name),
                )
            elif match := re.match(CirctDut.INPUT_VALID_PATTERN, name):
                input_numbers.add(int(match.group(1)))
            elif match := re.match(CirctDut.OUTPUT_VALID_PATTERN, name):
                idx = int(match.group(1))
                assert idx not in outputs
                outputs[idx] = self.get_output_port(f"out{idx}")

        # Collect all inputs
        input_numbers -= mem_input_numbers
        all_input_numbers = sorted(input_numbers | mem_input_numbers)
        port_list: dict[int, HandshakeInputPort | CirctMemory] = {}

        for num in all_input_numbers:
            if num in mem_input_numbers:
                loads = mem_loads.get(num, {})
                stores = mem_stores.get(num, {})
                assert set(loads.keys()) == set(range(len(loads))), \
                    f"non-contiguous load indices for in{num}: {set(loads.keys())}"
                assert set(stores.keys()) == set(range(len(stores))), \
                    f"non-contiguous store indices for in{num}: {set(stores.keys())}"
                port_list[num] = CirctMemory(
                    [loads[i] for i in range(len(loads))],
                    [stores[i] for i in range(len(stores))],
                )
            else:
                port_list[num] = self.get_input_port(f"in{num}")

        # Check that output indices are contiguous
        output_keys = set(outputs.keys())
        assert output_keys == set(range(len(outputs))), \
            f"non-contiguous output indices: {output_keys}"

        self.inputs = [port_list[k] for k in all_input_numbers]
        self.outputs = [outputs[i] for i in range(len(outputs))]

        num_inputs = sum(1 for p in self.inputs if isinstance(p, HandshakeInputPort))
        num_mems = sum(1 for p in self.inputs if isinstance(p, CirctMemory))
        mem_summary = ", ".join(
            f"in{num} (ld = {len(p.loads)}, st = {len(p.stores)})"
            for num, p in zip(all_input_numbers, self.inputs)
            if isinstance(p, CirctMemory)
        )
        print(f"found {num_inputs} input(s), {len(self.outputs)} output(s), "
            f"and {num_mems} memorie(s): {mem_summary}")

    async def run(self, args: list[int | None | MemoryState]) -> tuple[list[Any], list[MemoryState]]:
        """
        Simulates the DUT by sending the given inputs and waiting for outputs.
        Returns (outputs, memory_states) where memory_states is in the same
        order as the memory ports appear in args.
        """
        assert len(args) == len(self.inputs), \
            f"mismatched number of args: got {len(args)}, expected {len(self.inputs)}"

        # Set up memory states
        for port, arg in zip(self.inputs, args):
            if isinstance(port, CirctMemory):
                assert isinstance(arg, MemoryState)
                port.state = MemoryState(arg)

        # Push all scalar/control inputs concurrently
        input_tasks = []
        for port, arg in zip(self.inputs, args):
            if isinstance(port, HandshakeInputPort):
                assert not isinstance(arg, MemoryState)
                input_tasks.append(cocotb.start_soon(port.send(arg)))
        for task in input_tasks:
            await task

        # Wait for outputs
        outputs = [await port.read() for port in self.outputs]

        # Collect final memory states in order
        final_mems = [
            MemoryState(port.state)
            for port in self.inputs
            if isinstance(port, CirctMemory)
        ]

        return outputs, final_mems
