name: Setup Toolchains
description: Install various build dependencies
inputs:
  token:
    description: GitHub token for downloading releases
    required: true
runs:
  using: composite
  steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        rustflags: ""
    - uses: leanprover/lean-action@v1
      with:
        lake-package-directory: wavelet-core/lean
        auto-config: false
    - uses: ./.github/actions/setup-cvc5
      with:
        version: 1.3.3
        token: ${{ inputs.token }}
    - shell: bash
      run: |
        case "${{ runner.os }}" in
          Linux)
            sudo apt-get update
            sudo apt-get install -y lld
            ;;
          macOS)
            brew install lld
            ;;
        esac
