import Mathlib.Data.Vector.Basic

import Wavelet.Op
import Wavelet.Seq
import Wavelet.Dataflow
import Wavelet.Compile
import Wavelet.Lemmas

import Wavelet.Simulation.Relation
import Wavelet.Simulation.Lemmas

namespace Wavelet.Simulation.Ret

open Wavelet.Op Wavelet.Seq Wavelet.Dataflow Wavelet.Compile
open Relation Lemmas

theorem expr_outputs_nodup :
  (compileExpr.exprOutputs χ m n pathConds).toList.Nodup
:= by
  simp only [
    compileExpr.exprOutputs, Vector.toList_append, Vector.toList_push,
    Vector.toList_map, Vector.toList_range]
  apply List.Nodup.append
  · apply List.Nodup.map _ List.nodup_range
    simp [Function.Injective]
  · apply List.Nodup.append
    · apply List.Nodup.map _ List.nodup_range
      simp [Function.Injective]
    · simp
    · simp
  · simp
    apply List.disjoint_iff_ne.mpr
    simp

theorem final_exprOutputs_finIdxOf?_tail_cond :
  (compileExpr.retChans (n := n) χ [] ++
    (compileExpr.tailArgs (m := m) χ []).push (.tail_cond [])).finIdxOf?
    (.tail_cond []) = some (⟨n + m, by simp⟩)
  := by
  simp only [compileExpr.retChans, compileExpr.tailArgs]
  apply Vector.finIdxOf?_eq_some_iff.mpr
  constructor
  · simp [Vector.get_eq_getElem]
  · intros j hj hget
    simp [Vector.get_eq_getElem, Vector.getElem_append] at hget
    split at hget
    · simp at hget
    · simp [Vector.getElem_push] at hget
      omega

theorem final_exprOutputs_finIdxOf?_tail_args
  (hi : i < m) :
  (compileExpr.retChans (n := n) χ [] ++
    (compileExpr.tailArgs (m := m) χ []).push (.tail_cond [])).finIdxOf?
    (.tail_arg i []) = some (⟨n + i, by omega⟩)
  := sorry

theorem path_conds_nodup_alt
  (hnodup : (pathConds.map Prod.snd).Nodup)
  (hpath_conds : ((b, condName) :: tailConds).Sublist pathConds) :
  (b', condName) ∉ tailConds := by grind

universe u
variable (Op : Type u) (χ : Type u) (V S)
variable [instArity : Arity Op] [DecidableEq χ] [instInterp : Interp Op V S]

/-- Intermediate channel maps after the `forwardc` firing,
but before the `merge`s finish. -/
def intermChans
  (ec : Seq.Config Op χ V S m n)
  (pc : Dataflow.Config Op (ChanName χ) V S m n)
  (retVars : Vector χ n)
  (retVals : Vector V n)
  (pathConds : List (Bool × ChanName χ))
  (name : ChanName χ)
  : List V :=
  let junk := Interp.junkVal (self := instInterp) Op S
  let falseVal := Interp.fromBool Op S false
  match (
    compileExpr.retChans (n := n) χ pathConds ++
    (compileExpr.tailArgs (m := m) χ pathConds).push
    (ChanName.tail_cond pathConds)
  ).finIdxOf? name with
  | some i => [(retVals ++ (Vector.replicate m junk).push falseVal)[i]]
  | x =>
    if name ∈ compileExpr.varNames χ ec.pathConds retVars then
      []
    else
      -- `merge_cond` channels outside `pathConds` should be empty
      match name with
      | .merge_cond condName =>
        if (true, condName) ∈ pathConds then
          [instInterp.fromBool true]
        else if (false, condName) ∈ pathConds then
          [instInterp.fromBool false]
        else []
      | _ => pc.chans name

/-- Descibes the effect of the `merge`s generated by the conditionals. -/
theorem sim_step_ret_merges
  (ec : Seq.Config Op χ V S m n)
  (pc : Dataflow.Config Op (ChanName χ) V S m n)
  (hlive_vars : pc.chans = SimR.varsToChans _ _ _ _ ec)
  (hmerges : SimR.HasMerges _ _ _ m n pc.proc.atoms pathConds)
  (hpath_conds : pathConds.Sublist ec.pathConds)
  (hpath_conds_nodup : (ec.pathConds.map Prod.snd).Nodup)
  (hsteps :
    Dataflow.Config.StepPlus Op (ChanName χ) V S pc
    { proc := pc.proc,
      chans := intermChans _ _ _ _ ec pc vars retVals pathConds
      state := pc.state })
  : Dataflow.Config.StepPlus Op (ChanName χ) V S pc
    { proc := pc.proc,
      chans := intermChans _ _ _ _ ec pc vars retVals []
      state := pc.state }
  := by
  induction pathConds with
  | nil => exact hsteps
  | cons headCond tailConds ih =>
    rcases headCond with ⟨condBool, condName⟩
    simp only [SimR.HasMerges] at hmerges
    have ⟨hhead_merge, hmerges_rest⟩ := hmerges
    simp [compileExpr.brMerge] at hhead_merge
    -- Pop the merge condition (exists by `hlive_vars`)
    have hmem_cond_path_conds : (condBool, condName) ∈ ec.pathConds :=
      List.Sublist.mem (by simp) hpath_conds
    have hnot_mem_cond_tail_conds {b} : (b, condName) ∉ tailConds :=
      path_conds_nodup_alt hpath_conds_nodup hpath_conds
    have ⟨chans₁, hpop_cond, hchans₁⟩ := pop_val_singleton_rewrite _ _
      (map := intermChans _ _ _ _ ec pc vars retVals ((condBool, condName) :: tailConds))
      (name := .merge_cond condName)
      (val := instInterp.fromBool condBool)
      (by
        simp [intermChans]
        rw [Vector.finIdxOf?_eq_none_iff.mpr]
        · simp [compileExpr.varNames, compileExpr.varName]
          if h : condBool = true then
            simp [h] at hmem_cond_path_conds ⊢
          else
            simp [h] at hmem_cond_path_conds ⊢
            intros h
            simp [hnot_mem_cond_tail_conds] at h
        · simp [compileExpr.retChans, compileExpr.tailArgs])
    -- Pop `compileExpr.exprOutputs`
    have ⟨chans₂, exprOutputs, hpop_expr_outputs, hchans₂, hexpr_outputs⟩ :=
      pop_vals_singleton_rewrite _ _
      (map := chans₁)
      (names := compileExpr.exprOutputs χ m n ((condBool, condName) :: tailConds))
      (λ name val =>
        match name with
        | .dest i _ => ∃ (h : i < n), val = retVals[i]
        | .tail_arg _ _ => val = Interp.junkVal (self := instInterp) Op S
        | .tail_cond _ =>
          val = instInterp.fromBool condBool
        | _ => False)
      (by apply expr_outputs_nodup)
      (by sorry)
    -- Fire `merge`
    -- Some manipulation to match the preconditions of `step_merge`
    have :
      compileExpr.exprOutputs χ m n ((condBool, condName) :: tailConds)
      = if condBool = true then
          compileExpr.exprOutputs χ m n ((true, condName) :: tailConds)
        else
          compileExpr.exprOutputs χ m n ((false, condName) :: tailConds)
    := by split <;> (rename_i h; simp [h])
    simp only [this] at hpop_expr_outputs
    have hstep : Dataflow.Config.Step _ _ _ _
      { proc := pc.proc,
        chans := intermChans _ _ _ _ ec pc vars retVals ((condBool, condName) :: tailConds)
        state := pc.state } _
      := Dataflow.Config.Step.step_merge
        hhead_merge
        hpop_cond
        (instInterp.unique_fromBool_toBool _)
        hpop_expr_outputs
    -- Simplify pushes
    rw [push_vals_empty_rewrite] at hstep
    rotate_left
    · apply expr_outputs_nodup
    · intros name hname
      -- simp [compileExpr.exprOutputs] at hname
      simp [hchans₂, hchans₁, intermChans]
      intros h₁ h₂
      split <;> rename_i h₃
      · have := Vector.finIdxOf?_eq_none_iff.mpr h₁
        simp only [compileExpr.exprOutputs] at this
        simp [compileExpr.retChans, compileExpr.tailArgs, this] at h₃
      · simp
        intros h₄
        split <;> rename_i h₅
        · simp [compileExpr.exprOutputs] at hname
        · simp [hlive_vars, SimR.varsToChans]
          simp [compileExpr.exprOutputs] at hname
          rcases hname with ⟨_, _, hname⟩ | ⟨_, _, hname⟩ | hname
          · simp [← hname]
          · simp [← hname]
          · simp [hname]
    -- Connect `hsteps` and `hstep`
    replace hsteps := Relation.TransGen.tail hsteps hstep
    exact ih hmerges_rest (by grind)
      (step_plus_eq _ _ _ _ hsteps (by
        -- Some simplification to satisfy IH
        simp
        funext name
        simp [intermChans, compileExpr.exprOutputs, compileExpr.retChans,
          compileExpr.tailArgs]
        split <;> rename_i h₁
        · rename_i i
          simp [h₁]
          sorry
        · replace h₁ := Option.eq_none_iff_forall_ne_some.mpr h₁
          -- have h₁' := Vector.finIdxOf?_eq_none_iff.mp h₁
          simp [h₁]
          simp [hchans₂]
          simp only [compileExpr.exprOutputs]
          split <;> rename_i h₂
          · simp at h₂
            simp [compileExpr.varNames, compileExpr.varName,
              hlive_vars, SimR.varsToChans]
            rcases h₂ with ⟨_, _, h₂⟩ | ⟨_, _, h₂⟩ | h₂
            · simp [← h₂]
            · simp [← h₂]
            · simp [h₂]
          · simp [hchans₁]
            split <;> rename_i h₃
            · simp [h₃, compileExpr.varNames, compileExpr.varName,
                hnot_mem_cond_tail_conds]
            · simp [intermChans, compileExpr.retChans, compileExpr.tailArgs,
                Vector.finIdxOf?_eq_none_iff.mpr h₂]
              split <;> rename_i h₄
              · rfl
              · split <;> rename_i chanName'
                · grind
                · rfl))

/- TODO: Fix proof performance -/
set_option maxHeartbeats 300000

theorem sim_step_ret
  (hnz : m > 0 ∧ n > 0)
  (ec ec' : Seq.Config Op χ V S m n)
  (pc : Dataflow.Config Op (ChanName χ) V S m n)
  (hsim : SimR _ _ _ _ hnz ec pc)
  (hstep : Config.Step Op χ V S ec ec')
  (hexpr : ec.expr = .cont (.ret vars)) :
  ∃ pc',
    Config.StepPlus Op (ChanName χ) V S pc pc' ∧
    SimR _ _ _ _ hnz ec' pc' := by
  have ⟨
    heq_state,
    hlive_vars,
    hdefined_vars_no_dup,
    hdefined_vars,
    hpath_conds_order,
    hpath_conds_nodup,
    hmerges,
    ⟨
      rest, carryInLoop, ctxLeft, ctxCurrent, ctxRight,
      hatoms,
      hcomp_fn,
      hrest,
      hret,
      hcont,
    ⟩,
  ⟩ := hsim
  -- An alternative description of `rest`
  have hrest' :
    compileFn.bodyComp Op χ V S hnz ec.fn ++ compileFn.resultSteers Op χ V m n = rest
  := by
    simp [compileFn] at hcomp_fn
    exact hcomp_fn
  have ⟨hcarryInLoop, hwf_expr, hcurrent⟩ := hcont (.ret vars) hexpr
  simp [compileExpr] at hcurrent
  -- Deduce some facts from `hstep`
  cases hstep with
  | step_br hexpr' | step_tail hexpr' | step_op hexpr' =>
    simp [hexpr] at hexpr'
  | step_ret hexpr' hvars =>
    rename_i inputVals vars'
    simp [hexpr] at hexpr'
    subst hexpr'
    cases hwf_expr with | wf_ret hvars_nodup =>
    -- Some abbreviations
    generalize hvar_names :
      compileExpr.varNames χ ec.pathConds vars = varNames
    generalize hret_chans :
      compileExpr.retChans (n := n) χ ec.pathConds = retChans
    generalize hjunk :
      Interp.junkVal (self := instInterp) Op S = junk
    generalize hfalse :
      Interp.fromBool (self := instInterp) Op S false = falseVal
    generalize hforwardc_outputs :
      retChans ++
      (compileExpr.tailArgs (m := m) χ ec.pathConds).push
      (ChanName.tail_cond ec.pathConds)
      = forwardcOutputs
    simp only [hvar_names, hret_chans, hjunk, hfalse, hforwardc_outputs] at hcurrent
    -- Step 1: Fire the `forwardc`.
    have ⟨chans₁, retVals, hpop_ret_vals, hchans₁, hret_vals⟩ :=
      pop_vals_singleton_rewrite _ _
      (map := pc.chans)
      (names := varNames)
      (λ name val =>
        ∃ var,
          name = .var var ec.pathConds ∧
          ec.vars.getVar _ _ var = some val)
      (by
        simp only [← hvar_names, compileExpr.varNames, Vector.toList_map]
        apply List.Nodup.map _ hvars_nodup
        simp [Function.Injective, compileExpr.varName])
      (by
        simp [← hvar_names, hlive_vars, compileExpr.varNames,
          compileExpr.varName, SimR.varsToChans]
        have := Vector.mapM_some_implies_all_some hvars
        intros v hmem_v
        have ⟨val, _, hval⟩ := this v hmem_v
        exists val
        simp [VarMap.getVar, hval])
    have hmem_forwardc :
      AtomicProc.forwardc
        varNames ((Vector.replicate m junk).push falseVal)
        forwardcOutputs
        ∈ pc.proc.atoms
    := sorry -- grind
    have hsteps₁ : Dataflow.Config.StepPlus _ _ _ _ pc _
      := Relation.TransGen.single (Dataflow.Config.Step.step_forwardc hmem_forwardc hpop_ret_vals)
    -- Simplify pushes
    rw [push_vals_empty_rewrite] at hsteps₁
    rotate_left
    · simp only [← hforwardc_outputs, ← hret_chans, compileExpr.tailArgs, compileExpr.retChans]
      apply expr_outputs_nodup
    · simp only [← hforwardc_outputs, ← hret_chans, compileExpr.retChans, compileExpr.tailArgs]
      intros name hmem_name
      simp at hmem_name
      simp [hchans₁, ← hvar_names, compileExpr.varNames,
        compileExpr.varName, hlive_vars, SimR.varsToChans]
      rcases hmem_name with ⟨_, _, h⟩ | ⟨_, _, h⟩ | h
      · simp [← h]
      · simp [← h]
      · simp [h]
    simp only [hchans₁] at hsteps₁
    -- Step 2: Fire the sequence of `merge`s (through `SimR.HasMerges`)
    -- so that `dest i []`, `tail_arg i []`, `tail_cond []` channels are ready.
    have hmerge_init :
      Dataflow.Config.StepPlus Op (ChanName χ) V S pc
      { proc := pc.proc,
        chans := intermChans _ _ _ _ ec pc vars retVals ec.pathConds
        state := pc.state }
    := by
      apply step_plus_eq
      apply hsteps₁
      simp
      funext name
      simp [intermChans, ← hforwardc_outputs, ← hret_chans, ← hjunk, ← hfalse]
      sorry -- grind
    have hsteps₂ := sim_step_ret_merges _ _ _ _ ec pc
      hlive_vars hmerges (by simp)
      hpath_conds_nodup hmerge_init
    -- Step 3: Fire the `fork` in `compileFn`.
    simp only [compileFn, compileFn.resultSteers] at hcomp_fn
    have ⟨chans₂, hpop_tail_cond, hchans₂⟩ := pop_val_singleton_rewrite _ _
      (map := intermChans _ _ _ _ ec pc vars retVals [])
      (name := .tail_cond [])
      (val := instInterp.fromBool false)
      (by simp [intermChans, final_exprOutputs_finIdxOf?_tail_cond])
    have hmem_fork :
      .fork (ChanName.tail_cond [])
        #v[.tail_cond_carry, .tail_cond_steer_dests, .tail_cond_steer_tail_args]
      ∈ pc.proc.atoms
    := by grind
    have hsteps₃ : Dataflow.Config.StepPlus _ _ _ _ pc _
      := Relation.TransGen.tail hsteps₂
        (Dataflow.Config.Step.step_fork hmem_fork hpop_tail_cond)
    -- Simplify pushes
    rw [push_vals_empty_rewrite] at hsteps₃
    rotate_left
    · simp
    · sorry -- should be easy
    simp at hsteps₃
    replace ⟨pc₁, hpc₁, hsteps₃⟩ := exists_eq_left.mpr hsteps₃
    -- Step 4: Fire the first `steer` in `compileFn` for return values.
    have ⟨chans₃, hpop_tail_cond_steer_dests, hchans₃⟩ := pop_val_singleton_rewrite _ _
      (map := pc₁.chans)
      (name := .tail_cond_steer_dests)
      (val := instInterp.fromBool false)
      (by simp [hpc₁, List.finIdxOf?, List.findFinIdx?, List.findFinIdx?.go])
    have ⟨chans₄, destVals, hpop_dest_vals, hchans₄, hdest_vals⟩ :=
      pop_vals_singleton_rewrite _ _
      (map := chans₃)
      (names := (Vector.range n).map (.dest · []))
      (λ name val =>
        match name with
        | .dest i _ => ∃ (h : i < n), val = retVals[i]
        | _ => False)
      (by
        simp [Vector.toList_map, Vector.toList_range]
        apply List.Nodup.map _ List.nodup_range
        simp [Function.Injective])
      (by sorry)
    have hmem_steer_dests :
      .steer false
        .tail_cond_steer_dests
        ((Vector.range n).map (.dest · []))
        ((Vector.range n).map .final_dest)
      ∈ pc₁.proc.atoms
    := by grind
    have hsteps₄ : Dataflow.Config.StepPlus _ _ _ _ pc _
      := Relation.TransGen.tail hsteps₃
        (Dataflow.Config.Step.step_steer
          hmem_steer_dests
          hpop_tail_cond_steer_dests
          hpop_dest_vals
          (instInterp.unique_fromBool_toBool _))
    -- Simplify pushes
    rw [push_vals_empty_rewrite] at hsteps₄
    rotate_left
    · simp [Vector.toList_map, Vector.toList_range]
      apply List.Nodup.map _ List.nodup_range
      simp [Function.Injective]
    · sorry -- TODO: some map simplification
    simp at hsteps₄
    replace ⟨pc₂, hpc₂, hsteps₄⟩ := exists_eq_left.mpr hsteps₄
    -- Step 5: Fire the second `steer` in `compileFn` for tail call args.
    have ⟨chans₅, hpop_tail_cond_steer_tail_args, hchans₅⟩ := pop_val_singleton_rewrite _ _
      (map := pc₂.chans)
      (name := .tail_cond_steer_tail_args)
      (val := instInterp.fromBool false)
      (by
        simp [hpc₂, hchans₄, hchans₃, hpc₁,
          List.finIdxOf?, List.findFinIdx?, List.findFinIdx?.go])
    have ⟨chans₆, tailArgVals, hpop_tail_arg_vals, hchans₆, htail_arg_vals⟩ :=
      pop_vals_singleton_rewrite _ _
      (map := chans₅)
      (names := (Vector.range m).map (.tail_arg · []))
      (λ name val => True)
      (by
        simp [Vector.toList_map, Vector.toList_range]
        apply List.Nodup.map _ List.nodup_range
        simp [Function.Injective])
      (by
        simp
        intros i hi
        simp [hchans₅, hpc₂, hchans₄, hchans₃, hpc₁,
          List.finIdxOf?, List.findFinIdx?, List.findFinIdx?.go,
          hchans₂, intermChans,
          final_exprOutputs_finIdxOf?_tail_args hi])
    have hmem_steer_tail_args :
      .steer true
        .tail_cond_steer_tail_args
        ((Vector.range m).map (.tail_arg · []))
        ((Vector.range m).map .final_tail_arg)
      ∈ pc₂.proc.atoms
    := by grind
    have hsteps₅ : Dataflow.Config.StepPlus _ _ _ _ pc _
      := Relation.TransGen.tail hsteps₄
        (Dataflow.Config.Step.step_steer
          hmem_steer_tail_args
          hpop_tail_cond_steer_tail_args
          hpop_tail_arg_vals
          (instInterp.unique_fromBool_toBool _))
    simp at hsteps₅
    replace ⟨pc₃, hpc₃, hsteps₅⟩ := exists_eq_left.mpr hsteps₅
    -- Step 6: Fire the first `carry` in `compileFn`.
    have ⟨chans₆, hpop_tail_cond_steer_tail_args, hchans₆⟩ := pop_val_singleton_rewrite _ _
      (map := pc₃.chans)
      (name := .tail_cond_carry)
      (val := instInterp.fromBool false)
      (by
        simp [hpc₃, hchans₆, hchans₅, hpc₂, hchans₄, hchans₃, hpc₁,
          List.finIdxOf?, List.findFinIdx?, List.findFinIdx?.go])
    have hmem_carry :
      pc₃.proc.atoms = [] ++ [compileFn.initCarry _ _ _ ec.fn carryInLoop] ++ rest
    := by simp [hpc₃, hpc₂, hpc₁, hatoms]
    simp only [compileFn.initCarry, hcarryInLoop] at hmem_carry
    have hsteps₆ : Dataflow.Config.StepPlus _ _ _ _ pc _
      := Relation.TransGen.tail hsteps₅
        (Dataflow.Config.Step.step_carry_false
          hmem_carry
          hpop_tail_cond_steer_tail_args
          (instInterp.unique_fromBool_toBool _))
    simp at hsteps₆
    replace ⟨pc', hpc', hsteps₆⟩ := exists_eq_left.mpr hsteps₆
    -- Step 7: Prove preservation of invariants.
    exists pc'
    constructor
    · exact hsteps₆
    · and_intros
      · simp only [hpc', hpc₃, hpc₂, hpc₁, heq_state]
      · -- varsToChans
        sorry
      · simp
      · simp
        -- TODO: should be easy
        sorry
      · simp
      · simp
      · simp [SimR.HasMerges]
      · simp [hpc', compileFn.initCarry, compileFn]
        exact hrest'

end Wavelet.Simulation.Ret
