name: Build Wavelet
on: [push, workflow_dispatch]
env:
  CACHE_VERSION: v3
jobs:
  unit-tests:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
          - runs-on: ubuntu-24.04-arm
          - runs-on: macos-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - uses: ./.github/actions/setup-toolchains
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo fmt -- --check
      - run: cargo test --all
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - run: git submodule update --depth 1 --init --recursive integration-tests/circt
      - uses: ./.github/actions/build-circt
        with:
          source-dir: integration-tests/circt
          build-dir: integration-tests/build/circt
      - uses: ./.github/actions/setup-toolchains
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/setup-verilator
        with:
          version: v5.044
      - run: cargo build
      - run: make tests
        working-directory: integration-tests
  check-proofs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: wavelet-core/lean
          build-args: --wfail Thm
