name: Build Wavelet
on: [push]
env:
  Z3_VERSION: 4.15.4
  CACHE_VERSION: v1
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: wavelet-core/lean
          auto-config: false
      - run: |
          wget https://github.com/Z3Prover/z3/releases/download/z3-${Z3_VERSION}/z3-${Z3_VERSION}-x64-glibc-2.39.zip
          unzip z3-${Z3_VERSION}-*.zip
          sudo cp z3-${Z3_VERSION}-*/bin/z3 /usr/local/bin/
          z3 --version
      - run: cargo build
      - run: cargo fmt -- --check
      - run: cargo test --all\
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: wavelet-core/lean
          auto-config: false
      # Cache CIRCT build
      - uses: actions/cache@v4
        with:
          path: integration-tests/build
          key: circt-build-${{ env.CACHE_VERSION }}-${{ runner.os }}-${{ hashFiles('.gitmodules', 'integration-tests/circt') }}
          restore-keys: |
            circt-build-${{ env.CACHE_VERSION }}-${{ runner.os }}-
      - run: cargo build
      - run: |
          sudo apt-get update
          sudo apt-get install -y clang lld
      # Build CIRCT/hlstool
      - run: |
          cmake circt/llvm/llvm -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_ASSERTIONS=OFF \
            -DLLVM_TARGETS_TO_BUILD=host \
            -DLLVM_ENABLE_PROJECTS=mlir \
            -DLLVM_EXTERNAL_PROJECTS=circt \
            -DLLVM_EXTERNAL_CIRCT_SOURCE_DIR=circt \
            -DLLVM_ENABLE_LLD=ON
          cmake --build build --target hlstool --parallel 1
        working-directory: integration-tests
      - run: make tests
        working-directory: integration-tests
  check-proofs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: wavelet-core/lean
          build-args: Thm
